### ISSUE TITLE
zipalign is removed in new sdk tools

### ISSUE THREAD

**Issue by fashioncj** [plum-umd/redexer#23]
maybe need change the location at the apk.rb

**Comment by jsjeon** [comment]
We can do some hacks like this: https://github.com/calabash/calabash-android/commit/c6ca427550ebd4a998fce96fb451079ca401616c

But, in general, we ask users to set paths to Android base tools, including `aapt` and `zipalign`.  That's why we call them without any prefix paths.  I updated the README to describe how to set it up: https://github.com/plum-umd/redexer/commit/78d8f09d918dc98b9784c6a9a7dde977da4c34c4
