### ISSUE TITLE
`trans_adder` pass mangles method links

### ISSUE THREAD

**Issue by kmicinski** [plum-umd/redexer#24]
When the `trans_adder` pass runs during the logging phase for some APKs, it causes method identifiers to be mangled when the resulting APK is finally dumped. This results in a large set of verification errors because methods will be shifted to unpredictable places.

For example, in the `com.apalon.myclockfree` APK, running the `trans_adder` phase causes the resulting APK to break. Running everything _but_ the `trans_adder` phase works.

Here is a link to the APK in question:

http://www.speedyshare.com/M4TK4/com.apalon.myclockfree.apk

It must be run on the `logging` branch

**Comment by kmicinski** [comment]
@jsjeon Do you have any tips for why this could be happening? Is there anything I should be particularly careful of when handling this code? If not, I can continue debugging it. I'm afraid that there might be something weird with the interaction of this code and the dump code.

Here's a manifestation of the verification errors:

```
I/dex2oat (15143): Verification error in com.mopub.common.MoPub$LocationAwareness[] com.mopub.common.MoPub$LocationAwareness.values()
I/dex2oat (15143): invoke type (METHOD_VIRTUAL) does not match method  type of android.os.Bundle a.e.a(android.content.Intent)
I/dex2oat (15143): 'this' argument 'Precise Reference: com.mopub.common.MoPub$LocationAwareness[]' not instance of 'Precise Reference: a.e'
I/dex2oat (15143): com.mopub.common.MoPub$LocationAwareness[] com.mopub.common.MoPub$LocationAwareness.values() failed to verify: Rejecting invocation, expected 1 arguments, found 1 or more.MoPub$LocationAwareness.values(): [0x2]
E/dex2oat (15143): Verification failed on class com.mopub.common.MoPub$LocationAwareness in /data/app/com.apalon.myclockfree-1/base.apk because: Verifier rejected class com.mopub.common.MoPub$LocationAwareness due to bad method com.mopub.common.MoPub$LocationAwareness[] com.mopub.common.MoPub$LocationAwareness.values()
I/dex2oat (15143): Verification error in com.mopub.common.UrlAction[] com.mopub.common.UrlAction.values()
I/dex2oat (15143): invoke type (METHOD_VIRTUAL) does not match method  type of android.os.Bundle a.e.b(android.content.Intent)
I/dex2oat (15143): 'this' argument 'Reference: com.mopub.common.UrlAction[]' not instance of 'Precise Reference: a.e'
I/dex2oat (15143): com.mopub.common.UrlAction[] com.mopub.common.UrlAction.values() failed to verify: Rejecting invocation, expected 1 arguments, found 1 or more.es(): [0x2]
E/dex2oat (15143): Verification failed on class com.mopub.common.UrlAction in /data/app/com.apalon.myclockfree-1/base.apk because: Verifier rejected class com.mopub.common.UrlAction due to bad method com.mopub.common.UrlAction[] com.mopub.common.UrlAction.values()
```

**Comment by jsjeon** [comment]
If some _transition_ methods were not overridden, they won't appear in the dex, resulting in missed logging.  The main task of `trans_adder` is to add such transition methods.  It looked weird to me that those verification error have arisen at non-transition methods.  However, the signature of the callee (i.e., invoked methods, such as `a.e.a` and `a.e.b`) seems one of transition methods, since their input is `Intent` and output is `Bundle`.  Maybe, introducing quasi-empty transition methods mangled ProGuard's shuffling? :p

Anyhow, from the errors, I can guess the dex changes would look like this: say, for `...UrlAction.values()`, the last part of the method was:
```java
UrlAction[] values() {
  ...
  UrlAction[] res = ...;
  return res;
}
```
Then, that part after the instrumentation would look like:
```java
UrlAction[] values() {
  ...
  UrlAction[] res = ...;
  res.b(...); // where b refers to a.e.b
  return res;
}
```
That's why `this` pointer points to the return type of the caller method, not the expected one (`a.e`).  Well, I don't think `trans_adder` phase added such statement, then the question is which phase adds, and why.  In some phase, what we wanted to add would be:
```java
UrlAction[] values() {
  ...
  UrlAction[] res = ...;
  logger.log(res); // the logging statement should look like this.
  return res;
}
```
But, somehow, the receiver and target method are all screwed up?

**Comment by jsjeon** [comment]
Btw, does this line work correctly?
https://github.com/plum-umd/redexer/blob/master/src/ext/logging.ml#L208

I can see my comment somewhere around that line, saying:
> (* insert method sig first so that M.override can find method_id_item *)

and, as shown here:
https://github.com/plum-umd/redexer/blob/master/src/ext/logging.ml#L192
`M.new_sig` is called between `M.new_class` and `insert_void_no_arg`.  But, logging of `AsyncTask` didn't do so, so I wonder it is safe and working as expected.

**Comment by kmicinski** [comment]
It looks like this error is actually a little bit broader than I thought. Even if I totally turn off the part of redexer that adds in method bodies, the method table is still mangled for some apps.

For example, in one app I'm instrumenting one method is changed to (first line relevant):

```
    0  (00000000) sget-object         v0, Lcom/facebook/LoggingBehavior;->$VALUES [Lcom/facebook/LoggingBehavior;
>>> 1  (00000004) invoke-virtual      v0, [Lcom/facebook/LoggingBehavior;->clone()Ljava/lang/Object;
    2  (0000000a) move-result-object  v0
    3  (0000000c) check-cast          v0, [Lcom/facebook/LoggingBehavior;
    4  (00000010) return-object       v0
```

To:

```
    0  (00000000) sget-object         v5, Lcom/facebook/LoggingBehavior;->$VALUES [Lcom/facebook/LoggingBehavior;
>>> 1  (00000004) invoke-virtual      v5, Landroid/app/RemoteInput;->getResultKey()Ljava/lang/String;
    2  (0000000a) move-result-object  v5
    3  (0000000c) check-cast          v5, [Lcom/facebook/LoggingBehavior;
    4  (00000010) return-object       v5
```

I'm going to just force redexer to print the target of that call and figure out what place it's becoming changed to find where the bug is.

**Comment by jsjeon** [comment]
So, it's not about wrong instrumentations.  Method id reference is incorrectly shifted somehow.  One scenario I can come up with is, some same classes, e.g., Android support lib, are in both places---the target app and the logging library, and then, merging phase incorrectly reorganized method references.  But, I believe `dumper` module takes these into account: sorting, removing duplicates, and adjusting references if they're gone due to duplications.

Another case might be inconsistency, e.g., forgot to update method reference table at the top-most level in dex while introducing method_item.  I'm still suspecting the lack of `M.new_sig` call I mentioned above.

**Comment by kmicinski** [comment]
@jsjeon I just parsed your last comment and it confused me a little. You said that `new_sig` wasn't called, but that's exactly what `insrt_void_no_arg` is doing for the asynctask case, isn't it?

**Comment by jsjeon** [comment]
Well, I have not worked on `AsyncTask`, and thus wonder that part should make a call to `new_sig` so as to make the (logging) method addition _consistent_.
