### ISSUE TITLE
Building on Mac

### ISSUE THREAD

**Issue by algobardo** [plum-umd/redexer#7]
Hi,
i'm trying to build on Mac,
when i run configure i get 

checking if performance counters are usable...
result: no (cannot compile ocamlutil/stats_stubs.c.in)

however stats_stubs.o is generated, but making returns linking error

ld: warning: ignoring file ocamlutil/stats_stubs.o, file was built for i386 which is not the architecture being linked (x86_64): ocamlutil/stats_stubs.o
Undefined symbols for architecture x86_64:
  "_has_performance_counters", referenced from:
      .L172 in stats.o
      _camlStats__28 in stats.o
  "_read_pentium_perfcount", referenced from:
      .L215 in stats.o
      _camlStats__28 in stats.o
  "_reset_performance_counters", referenced from:
      .L178 in stats.o
      .L175 in stats.o
      _camlStats__28 in stats.o
  "_sample_pentium_perfcount_10", referenced from:
      .L168 in stats.o
      _camlStats__28 in stats.o
  "_sample_pentium_perfcount_20", referenced from:
      .L170 in stats.o
      _camlStats__28 in stats.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:

can you help me to build it ?

**Comment by matthewhammer** [comment]
I'm trying to compile CEAL and I'm getting the following error, which Kris got above:

```
Linking bytecode obj/x86_DARWIN/cilly.byte.exe
+ clang -Wl,-no_compact_unwind -o 'obj/x86_DARWIN/cilly.byte.exe'   '-L/usr/local/lib/ocaml' -g '/var/folders/t7/_4_c10rn4jxbn0qx2wrtyk480000gp/T/camlprim96cdda.c' '-lcamlstr' '-lunix' '-lunix' '-lstr' 'obj/x86_DARWIN/perfcount.o' '-lcamlrun' -I'/usr/local/lib/ocaml' -lcurses -lpthread
Undefined symbols for architecture x86_64:
  "_read_ppc", referenced from:
      _read_pentium_perfcount in perfcount.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "_none_", line 1:
Error: Error while building custom runtime system
make: *** [obj/x86_DARWIN/cilly.byte.exe] Error 2
```

What was the fix for this?

**Comment by kmicinski** [comment]
In our case I think the answer was to simply remove the old deprecated
performance counters (that used hardware counters) from redexer and use
software counters instead: that didn't link to this problematic function.
The old advice that fixed this was setting CCFLAGS=-arch i386 in the
configuration.

In general, though, these linking issues seem to be because there is some
weirdness with clang: I'm sorry I can't be more helpful than that though.

Maybe you could track down the hardware counters in CEAL and hack them out
like we did in redexer?

Kris
